const strings = {
  empty: 'You haven\'t posted any bounties. Click \'+ BOUNTY\' to post one.',
  view: 'View',
  delete: 'Delete',
  resolved: ' (CLOSED)',
  active: ' (ACTIVE)',
  expired: ' (EXPIRED)',
  nct: ' Nectar (NCT)',
  author: 'Author: ',
  expert: 'Expert: ',
  lastPay: 'Last Payout',
  messages: 'Messages: ',
  assertions: 'Assertions: ',
  files: 'Files: ',
  title: 'Bounties & Offers',
  newBounty: '+ Bounty',
  newOffer: '+ Offer',
  relay: 'Fund sidechain',
};
export default strings;